server.port: 8181

logging:
  level:
    root: DEBUG
    com.siemens.bt: DEBUG
    org.hibernate: INFO
    
graphql:
  servlet:
    mapping: /demo
    enabled: true
    corsEnabled: true
    
graphiql:
  mapping: /graphiql
  endpoint: /demo
  enabled: true